spring:
  datasource:
    url: jdbc:postgresql://localhost:${PARKFLOW_DB_PORT:6021}/parkflow_dev
    username: parkflow
    password: parkflow
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
