ALTER TABLE parking_sites
  ADD COLUMN IF NOT EXISTS max_capacity INT NOT NULL DEFAULT 0;

ALTER TABLE parking_session
  ADD COLUMN IF NOT EXISTS country_code VARCHAR(2) NOT NULL DEFAULT 'CO',
  ADD COLUMN IF NOT EXISTS entry_mode VARCHAR(20) NOT NULL DEFAULT 'VISITOR',
  ADD COLUMN IF NOT EXISTS no_plate BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS no_plate_reason VARCHAR(200);

ALTER TABLE vehicle
  ALTER COLUMN plate TYPE VARCHAR(20);

ALTER TABLE parking_session
  ALTER COLUMN plate TYPE VARCHAR(20);
