/**
 * Standardized error codes mirroring the backend ErrorCode enum.
 */
export enum ErrorCode {
  // Auth Errors
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_SESSION_EXPIRED = "AUTH_SESSION_EXPIRED",
  ACCESS_DENIED = "ACCESS_DENIED",
  AUTH_REFRESH_FAILED = "AUTH_REFRESH_FAILED",
  AUTH_DEVICE_LOCKED = "AUTH_DEVICE_LOCKED",

  // Business Errors
  COMPANY_NOT_FOUND = "COMPANY_NOT_FOUND",
  COMPANY_NAME_REQUIRED = "COMPANY_NAME_REQUIRED",
  COMPANY_ALREADY_EXISTS = "COMPANY_ALREADY_EXISTS",
  USER_EMAIL_ALREADY_EXISTS = "USER_EMAIL_ALREADY_EXISTS",
  LICENSE_EXPIRED = "LICENSE_EXPIRED",
  LICENSE_DISABLED = "LICENSE_DISABLED",
  PARKING_RATE_NOT_FOUND = "PARKING_RATE_NOT_FOUND",
  VEHICLE_PLATE_REQUIRED = "VEHICLE_PLATE_REQUIRED",
  TICKET_NOT_FOUND = "TICKET_NOT_FOUND",
  PRINT_AGENT_UNAVAILABLE = "PRINT_AGENT_UNAVAILABLE",
  DATABASE_CONSTRAINT_ERROR = "DATABASE_CONSTRAINT_ERROR",
  RESOURCE_CONFLICT = "RESOURCE_CONFLICT",
  DUPLICATE_ENTITY = "DUPLICATE_ENTITY",
  PRINT_ERROR = "PRINT_ERROR",

  // System Errors
  OPERATION_ERROR = "OPERATION_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  FIELD_ERROR = "FIELD_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  BAD_GATEWAY = "BAD_GATEWAY",

  // Frontend Specific
  NETWORK_ERROR = "NETWORK_ERROR",
  NETWORK_TIMEOUT = "NETWORK_TIMEOUT",
  NETWORK_OFFLINE = "NETWORK_OFFLINE",
  OFFLINE_NOT_SUPPORTED = "OFFLINE_NOT_SUPPORTED",
  LOCAL_STORAGE_FULL = "LOCAL_STORAGE_FULL",
  TAURI_COMMAND_ERROR = "TAURI_COMMAND_ERROR",
  SQLITE_ERROR = "SQLITE_ERROR",
  PRINTER_UNAVAILABLE = "PRINTER_UNAVAILABLE",
  DESKTOP_LICENSE_ERROR = "DESKTOP_LICENSE_ERROR",
  CASH_OPERATION_FAILED = "CASH_OPERATION_FAILED",
  SYNC_ERROR = "SYNC_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}
