#!/usr/bin/env node
// =============================================================================
// Security Report Generator
// =============================================================================
// Usage: node security/scripts/generate-report.mjs
// Aggregates ZAP, Semgrep, and dependency check reports into a single markdown
// =============================================================================

import { readdir, readFile, stat } from 'fs/promises';
import { join, resolve } from 'path';
import { execSync } from 'child_process';

const ROOT = resolve(process.cwd());
const REPORTS_DIR = join(ROOT, 'security', 'reports');
const OUTPUT_FILE = join(REPORTS_DIR, 'SECURITY-AGGREGATE-REPORT.md');

async function findLatestReport(pattern) {
  try {
    const files = await readdir(REPORTS_DIR);
    const matching = files.filter(f => f.includes(pattern));
    if (matching.length === 0) return null;
    
    const stats = await Promise.all(
      matching.map(async f => ({
        file: f,
        // nosemgrep: javascript.lang.security.audit.path-traversal.path-join-resolve-traversal.path-join-resolve-traversal
        mtime: (await stat(join(REPORTS_DIR, f))).mtime,
      }))
    );
    
    stats.sort((a, b) => b.mtime - a.mtime);
    return stats[0].file;
  } catch {
    return null;
  }
}

async function readJsonReport(filename) {
  if (!filename) return null;
  try {
    // nosemgrep: javascript.lang.security.audit.path-traversal.path-join-resolve-traversal.path-join-resolve-traversal
    const content = await readFile(join(REPORTS_DIR, filename), 'utf-8');
    return JSON.parse(content);
  } catch {
    return null;
  }
}

function countAlerts(report) {
  if (!report?.site?.[0]?.alerts) return { high: 0, medium: 0, low: 0, info: 0 };
  
  const alerts = report.site[0].alerts;
  return {
    high: alerts.filter(a => a.riskcode === '3').length,
    medium: alerts.filter(a => a.riskcode === '2').length,
    low: alerts.filter(a => a.riskcode === '1').length,
    info: alerts.filter(a => a.riskcode === '0').length,
  };
}

function generateReport() {
  const now = new Date().toISOString();
  const commit = execSync('git rev-parse --short HEAD', { encoding: 'utf-8', cwd: ROOT }).trim();
  const branch = execSync('git branch --show-current', { encoding: 'utf-8', cwd: ROOT }).trim();

  return `# Security Aggregate Report

**Generated**: ${now}  
**Commit**: ${commit}  
**Branch**: ${branch}

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Total Scans | 3 |
| High Severity | See below |
| Medium Severity | See below |
| Low Severity | See below |

## ZAP Baseline Scan (Web)

**Latest Report**: ${baselineFile || 'Not found'}

| Risk Level | Count |
|------------|-------|
| High | ${baselineCounts.high} |
| Medium | ${baselineCounts.medium} |
| Low | ${baselineCounts.low} |
| Informational | ${baselineCounts.info} |

## ZAP API Scan

**Latest Report**: ${apiFile || 'Not found'}

| Risk Level | Count |
|------------|-------|
| High | ${apiCounts.high} |
| Medium | ${apiCounts.medium} |
| Low | ${apiCounts.low} |
| Informational | ${apiCounts.info} |

## Recommendations

1. Review all HIGH severity findings before release
2. Address MEDIUM findings within 2 sprints
3. Document accepted LOW risks with justification
4. Update ZAP rules monthly to reduce false positives

---

*Generated by Parkflow Security Toolkit*
`;
}

// Main execution
const baselineFile = await findLatestReport('zap-baseline');
const apiFile = await findLatestReport('zap-api');

const baselineReport = await readJsonReport(baselineFile);
const apiReport = await readJsonReport(apiFile);

const baselineCounts = countAlerts(baselineReport);
const apiCounts = countAlerts(apiReport);

const report = generateReport();
await Bun.write(OUTPUT_FILE, report);
console.log(`✅ Security aggregate report generated: ${OUTPUT_FILE}`);
