package com.parkflow.modules.auth.entity;

public enum AuthAuditAction {
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGOUT,
  REFRESH,
  PASSWORD_CHANGED,
  OFFLINE_OPERATION,
  OFFLINE_SYNC,
  DEVICE_REVOKED,
  SETTINGS_RATE_CREATE,
  SETTINGS_RATE_UPDATE,
  SETTINGS_RATE_STATUS,
  SETTINGS_RATE_DELETE,
  SETTINGS_USER_CREATE,
  SETTINGS_USER_UPDATE,
  SETTINGS_USER_STATUS,
  SETTINGS_USER_PASSWORD_RESET,
  SETTINGS_PARAMETERS_UPDATE,
  SETTINGS_PARAMETERS_VALIDATE,
  SETTINGS_PARAMETERS_RESET,
  CASH_SESSION_OPEN,
  CASH_SESSION_CLOSE,
  CASH_MOVEMENT_POST,
  CASH_MOVEMENT_VOID,
  CASH_COUNT_SUBMITTED,
  CASH_CLOSING_PRINT
}
